// Type definitions for api-ape
// Project: https://github.com/codemeasandwich/api-ape

import { Server as HttpServer } from 'http'
import { IncomingMessage } from 'http'

/**
 * WebSocket instance type (compatible with ws library and native implementations)
 */
export interface ApeWebSocket {
    send(data: string | Buffer): void
    close(code?: number, reason?: string): void
    on(event: 'message', handler: (data: Buffer) => void): this
    on(event: 'close', handler: () => void): this
    on(event: 'error', handler: (err: Error) => void): this
    readonly readyState: number
    readonly CONNECTING: 0
    readonly OPEN: 1
    readonly CLOSING: 2
    readonly CLOSED: 3
}

// =============================================================================
// SERVER TYPES
// =============================================================================

/**
 * Controller context available as `this` inside controller functions
 */
export interface ControllerContext {
    /** Send to ALL connected clients */
    broadcast(type: string, data: any): void
    /** Send to all clients EXCEPT the caller */
    broadcastOthers(type: string, data: any): void
    /** Get count of connected clients */
    online(): number
    /** Get array of connected clientIds */
    getClients(): string[]
    /** Unique ID of the calling client (generated by api-ape) */
    clientId: string
    /** Session ID from cookie (set by outer framework, may be null) */
    sessionId: string | null
    /** Original HTTP request */
    req: IncomingMessage
    /** WebSocket instance */
    socket: ApeWebSocket
    /** Parsed user-agent info */
    agent: {
        browser: { name?: string; version?: string }
        os: { name?: string; version?: string }
        device: { type?: string; vendor?: string; model?: string }
    }
    /** Custom embedded values from onConnect */
    [key: string]: any
}

/**
 * Controller function type
 */
export type ControllerFunction<T = any, R = any> = (
    this: ControllerContext,
    data: T
) => R | Promise<R>

/**
 * Send function provided to onConnect
 */
export type SendFunction = {
    (type: string, data: any): void
    toString(): string
}

/**
 * After hook returned from onReceive/onSend
 */
export type AfterHook = (err: Error | null, result: any) => void

/**
 * Connection lifecycle hooks returned from onConnect
 */
export interface ConnectionHandlers {
    /** Values to embed into controller context */
    embed?: Record<string, any>
    /** Called before processing incoming message, return after hook */
    onReceive?: (queryId: string, data: any, type: string) => AfterHook | void
    /** Called before sending message, return after hook */
    onSend?: (data: any, type: string) => AfterHook | void
    /** Called on error */
    onError?: (errorString: string) => void
    /** Called when client disconnects */
    onDisconnect?: () => void
}

/**
 * onConnect callback signature
 */
export type OnConnectCallback = (
    socket: ApeWebSocket,
    req: IncomingMessage,
    send: SendFunction
) => ConnectionHandlers | void

/**
 * Server options for ape()
 */
export interface ApeServerOptions {
    /** Directory containing controller files */
    where: string
    /** Connection lifecycle hook */
    onConnect?: OnConnectCallback
}

/**
 * Initialize api-ape on a Node.js HTTP/HTTPS server
 */
declare function ape(server: HttpServer, options: ApeServerOptions): void

declare namespace ape {
    /** Broadcast to all connected clients */
    export function broadcast(type: string, data: any, excludeClientId?: string): void
    /** Get count of connected clients */
    export function online(): number
    /** Get all connected client clientIds */
    export function getClients(): string[]

    // Browser client methods (available when imported in browser context)
    /** Subscribe to broadcasts from the server */
    export function on<T = any>(type: string, handler: (message: { err?: Error; type: string; data: T }) => void): void
    /** Subscribe to connection state changes. Returns unsubscribe function. */
    export function onConnectionChange(handler: (state: 'offline' | 'walled' | 'disconnected' | 'connecting' | 'connected') => void): () => void
    /** Get current transport type */
    export function getTransport(): 'websocket' | 'polling' | null

    /** Call any server function dynamically (browser only) */
    export function message<T = any, R = any>(data?: T): Promise<R>
}

// Server-side default export (also works as browser client proxy)
export default ape

// =============================================================================
// BROWSER CLIENT (Default export in browser context)
// =============================================================================

/**
 * Unified browser client - auto-initializing Proxy that buffers calls until ready.
 * 
 * In browser context (via bundler or direct import), `import api from 'api-ape'`
 * returns this client instead of the server function.
 * 
 * Usage:
 *   import api from 'api-ape'
 *   api.message({ text: 'Hello!' })  // Buffered until connected
 *   api.on('message', (data) => {})  // Listen for broadcasts
 *   api.onConnectionChange((state) => {}) // Connection state updates
 */
export interface ApeBrowserClient extends ApeSender {
    /** Subscribe to broadcasts from the server */
    on<T = any>(type: string, handler: MessageHandler<T>): void

    /** Subscribe to connection state changes. Returns unsubscribe function. */
    onConnectionChange(handler: (state: ConnectionState) => void): () => void

    /** Get current transport type ('websocket' | 'polling' | null) */
    getTransport(): TransportType | null
}

// =============================================================================
// CLIENT TYPES
// =============================================================================

/**
 * Connection state enum values
 */
export type ConnectionState = 'offline' | 'walled' | 'disconnected' | 'connecting' | 'connected' | 'closing'

/**
 * Connection state enum object
 */
export declare const ConnectionState: {
    Offline: 'offline'
    Walled: 'walled'
    Disconnected: 'disconnected'
    Connecting: 'connecting'
    Connected: 'connected'
    Closing: 'closing'
}

/**
 * Message received from server
 */
export interface ReceivedMessage<T = any> {
    err?: Error | string
    type: string
    data: T
}

/**
 * Message handler callback
 */
export type MessageHandler<T = any> = (message: ReceivedMessage<T>) => void

/**
 * Proxy-based sender - any property access creates a callable path
 * Example: sender.users.list() calls type="/users/list"
 */
export interface ApeSender {
    [key: string]: ApeSender & (<T = any, R = any>(data?: T) => Promise<R>)
}

/**
 * Set receiver for specific message type or all messages
 */
export type SetOnReceiver = {
    (type: string, handler: MessageHandler): void
    (handler: MessageHandler): void
}

/**
 * Connected client interface
 */
export interface ApeClient {
    sender: ApeSender
    setOnReceiver: SetOnReceiver
    /** Subscribe to connection state changes. Returns unsubscribe function. */
    onConnectionChange: (handler: (state: ConnectionState) => void) => () => void
    /** Get current transport type ('websocket' | 'polling' | null) */
    getTransport: () => TransportType | null
}

/**
 * Transport type for connection
 */
export type TransportType = 'websocket' | 'polling'

/**
 * Connect socket function with configuration methods
 */
export interface ConnectSocket {
    (): ApeClient
    /** Enable auto-reconnection on disconnect */
    autoReconnect(): void
    /** Connection state enum */
    ConnectionState: typeof ConnectionState
}

/**
 * Client module default export
 */
declare const connectSocket: ConnectSocket

export { connectSocket }

// =============================================================================
// BROADCAST MODULE
// =============================================================================

export declare const broadcast: (type: string, data: any) => void
export declare const online: () => number
export declare const getClients: () => string[]
