/**
 * @fileoverview VS Code Extension for api-ape
 *
 * Provides IntelliSense and type checking for api-ape WebSocket APIs.
 */

const path = require("path");
const vscode = require("vscode");
const {
  LanguageClient,
  TransportKind,
} = require("vscode-languageclient/node");
const { registerExplorer } = require("./explorer");
const { setupFileWatcher } = require("./fileWatcher");

/** @type {LanguageClient | undefined} */
let client;

/** @type {vscode.StatusBarItem | undefined} */
let statusBarItem;

/** @type {NodeJS.Timeout | undefined} */
let autoGenerateDebounce;

/** @type {import('./explorer').EndpointTreeProvider | undefined} */
let explorerProvider;

/**
 * Check if the workspace is an api-ape project
 *
 * @returns {Promise<boolean>}
 */
async function isApiApeWorkspace() {
  const workspaceFolders = vscode.workspace.workspaceFolders;
  if (!workspaceFolders || workspaceFolders.length === 0) {
    return false;
  }

  // Check for api-ape in package.json
  const packageJsonFiles = await vscode.workspace.findFiles(
    "**/package.json",
    "**/node_modules/**",
    5
  );

  for (const file of packageJsonFiles) {
    try {
      const content = await vscode.workspace.fs.readFile(file);
      const json = JSON.parse(content.toString());
      const deps = { ...json.dependencies, ...json.devDependencies };

      if (deps["api-ape"]) {
        return true;
      }
    } catch {
      // Ignore parsing errors
    }
  }

  // Check for .api-ape directory or config file
  const configFiles = await vscode.workspace.findFiles(
    "**/.api-ape{,.json,/schema.json}",
    "**/node_modules/**",
    1
  );

  return configFiles.length > 0;
}

/**
 * Start the Language Server
 *
 * @param {vscode.ExtensionContext} context - Extension context
 */
function startLanguageClient(context) {
  // Path to the LSP server module
  const serverModule = context.asAbsolutePath(
    path.join("..", "api-ape-lsp", "src", "server.js")
  );

  // Server options
  const serverOptions = {
    run: {
      module: serverModule,
      transport: TransportKind.ipc,
    },
    debug: {
      module: serverModule,
      transport: TransportKind.ipc,
      options: { execArgv: ["--nolazy", "--inspect=6009"] },
    },
  };

  // Client options
  const clientOptions = {
    documentSelector: [
      { scheme: "file", language: "javascript" },
      { scheme: "file", language: "typescript" },
      { scheme: "file", language: "javascriptreact" },
      { scheme: "file", language: "typescriptreact" },
    ],
    synchronize: {
      configurationSection: "apiApe",
      fileEvents: vscode.workspace.createFileSystemWatcher("**/api/**/*.{js,ts}"),
    },
  };

  // Create and start the client
  client = new LanguageClient(
    "apiApeLsp",
    "api-ape Language Server",
    serverOptions,
    clientOptions
  );

  client.start();
}

/**
 * Trigger auto-generation of types (debounced)
 */
async function triggerAutoGenerate() {
  const config = vscode.workspace.getConfiguration("apiApe");
  const autoGenerate = config.get("autoGenerateTypes", true);

  if (!autoGenerate || !client) {
    return;
  }

  // Debounce to avoid generating on every keystroke
  if (autoGenerateDebounce) {
    clearTimeout(autoGenerateDebounce);
  }

  autoGenerateDebounce = setTimeout(async () => {
    try {
      const outputPath = config.get("typesOutputPath", ".api-ape");
      updateStatusBar("$(sync~spin) api-ape: generating types...", "Generating type definitions");

      const result = await client.sendRequest("workspace/executeCommand", {
        command: "apiApe.generateTypes",
        arguments: [outputPath],
      });

      if (result && result.success) {
        updateStatusBar("$(check) api-ape", "Types generated successfully");
        // Reset to normal status after 3 seconds
        setTimeout(() => updateStatusBar("$(zap) api-ape", "api-ape IntelliSense active"), 3000);
      }
    } catch (err) {
      console.error("Auto-generate types failed:", err);
      updateStatusBar("$(warning) api-ape", `Auto-generate failed: ${err.message}`);
    }
  }, 1000); // 1 second debounce
}


/**
 * Register commands
 *
 * @param {vscode.ExtensionContext} context - Extension context
 */
function registerCommands(context) {
  // Refresh schema command
  context.subscriptions.push(
    vscode.commands.registerCommand("apiApe.refreshSchema", async () => {
      if (client) {
        await client.sendRequest("workspace/executeCommand", {
          command: "apiApe.refreshSchema",
        });
        vscode.window.showInformationMessage("api-ape schema refreshed");
      }
    })
  );

  // Generate types command
  context.subscriptions.push(
    vscode.commands.registerCommand("apiApe.generateTypes", async () => {
      if (!client) {
        vscode.window.showErrorMessage("api-ape LSP not running");
        return;
      }

      const config = vscode.workspace.getConfiguration("apiApe");
      const outputPath = config.get("typesOutputPath", ".api-ape");

      try {
        const result = await client.sendRequest("workspace/executeCommand", {
          command: "apiApe.generateTypes",
          arguments: [outputPath],
        });

        if (result && result.success) {
          vscode.window.showInformationMessage(
            `api-ape types generated at ${result.typesPath}`
          );
        } else {
          vscode.window.showErrorMessage(
            `Failed to generate types: ${result?.error || "Unknown error"}`
          );
        }
      } catch (err) {
        vscode.window.showErrorMessage(`Failed to generate types: ${err.message}`);
      }
    })
  );

  // Configure server command
  context.subscriptions.push(
    vscode.commands.registerCommand("apiApe.configureServer", async () => {
      const config = vscode.workspace.getConfiguration("apiApe");
      const currentUrl = config.get("serverUrl", "http://localhost:3000");

      const newUrl = await vscode.window.showInputBox({
        prompt: "Enter api-ape server URL",
        value: currentUrl,
        placeHolder: "http://localhost:3000",
      });

      if (newUrl) {
        await config.update(
          "serverUrl",
          newUrl,
          vscode.ConfigurationTarget.Workspace
        );
        vscode.window.showInformationMessage(
          `api-ape server URL updated to ${newUrl}`
        );
      }
    })
  );
}

/**
 * Create and configure the status bar item
 *
 * @param {vscode.ExtensionContext} context - Extension context
 */
function createStatusBar(context) {
  statusBarItem = vscode.window.createStatusBarItem(
    vscode.StatusBarAlignment.Right,
    100
  );
  statusBarItem.command = "apiApe.showStatus";
  updateStatusBar("$(sync~spin) api-ape", "Connecting to api-ape server...");
  statusBarItem.show();
  context.subscriptions.push(statusBarItem);
}

/**
 * Update status bar text and tooltip
 *
 * @param {string} text - Status bar text
 * @param {string} [tooltip] - Tooltip text
 */
function updateStatusBar(text, tooltip) {
  if (statusBarItem) {
    statusBarItem.text = text;
    if (tooltip) {
      statusBarItem.tooltip = tooltip;
    }
  }
}

/**
 * Extension activation
 *
 * @param {vscode.ExtensionContext} context - Extension context
 */
async function activate(context) {
  console.log("api-ape extension activating...");

  // Check if this is an api-ape workspace
  const isApiApe = await isApiApeWorkspace();
  if (!isApiApe) {
    console.log("Not an api-ape workspace, skipping activation");
    return;
  }

  console.log("api-ape workspace detected, starting LSP...");

  // Create status bar
  createStatusBar(context);

  // Start the language client
  startLanguageClient(context);

  // Set up file watcher
  setupFileWatcher(context, client, triggerAutoGenerate, () => explorerProvider);

  // Register commands
  registerCommands(context);

  // Register status command
  context.subscriptions.push(
    vscode.commands.registerCommand("apiApe.showStatus", async () => {
      if (client) {
        try {
          const result = await client.sendRequest("workspace/executeCommand", {
            command: "apiApe.getStatus",
          });
          const items = [
            `Server: ${result?.serverConnected ? "Connected" : "Disconnected"}`,
            `Endpoints: ${result?.endpointCount || 0}`,
            `Schema Source: ${result?.schemaSource || "Unknown"}`,
          ];
          vscode.window.showInformationMessage(
            `api-ape Status: ${items.join(" | ")}`
          );
        } catch {
          vscode.window.showInformationMessage(
            "api-ape: Unable to get status"
          );
        }
      }
    })
  );

  // Wait for client to be ready, then update status and register explorer
  if (client) {
    client.onReady().then(async () => {
      // Register API Explorer TreeView
      explorerProvider = registerExplorer(context, client);

      try {
        // Try to fetch schema to verify connection
        const result = await client.sendRequest("workspace/executeCommand", {
          command: "apiApe.getStatus",
        });
        if (result?.serverConnected) {
          updateStatusBar("$(zap) api-ape", `Connected - ${result.endpointCount} endpoints`);
        } else if (result?.schemaSource === "file") {
          updateStatusBar("$(file) api-ape", `Using local schema - ${result.endpointCount} endpoints`);
        } else {
          updateStatusBar("$(warning) api-ape", "No schema available - start server or generate types");
        }
      } catch {
        updateStatusBar("$(zap) api-ape", "api-ape IntelliSense active");
      }
    }).catch(() => {
      updateStatusBar("$(error) api-ape", "Failed to start language server");
    });
  }
}

/**
 * Extension deactivation
 *
 * @returns {Promise<void>|undefined} Promise that resolves when client stops
 */
function deactivate() {
  if (client) {
    return client.stop();
  }
}

module.exports = { activate, deactivate };
