/**
 * @file SSS error codes
 */
"use strict";

/**
 * Error codes for SSS operations
 * @enum {string}
 */
const SSSError = {
  INVALID_THRESHOLD: "INVALID_THRESHOLD",
  INVALID_SHARE_COUNT: "INVALID_SHARE_COUNT",
  INSUFFICIENT_SHARES: "INSUFFICIENT_SHARES",
  INVALID_SHARE_FORMAT: "INVALID_SHARE_FORMAT",
  SHARE_INDEX_MISMATCH: "SHARE_INDEX_MISMATCH",
  DUPLICATE_SHARE_INDEX: "DUPLICATE_SHARE_INDEX",
  RECONSTRUCTION_FAILED: "RECONSTRUCTION_FAILED",
  INVALID_SECRET: "INVALID_SECRET",
};

module.exports = { SSSError };
